"""
Helpers used by the CLI that are import-light enough to call from `nengok init`
without pulling in the full orchestrator stack.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent


def write_config_file(
    *,
    config_path: Path,
    phoenix_base_url: str,
    phoenix_api_key: str | None,
    project_identifier: str,
    google_api_key: str | None = None,
    agent_runner: str | None = None,
) -> Path:
    """
    Render `~/.nengok/config.toml`.

    API keys are written to the file only if the caller passed them
    explicitly. The recommended pattern is to leave keys in the
    environment so the on-disk config can be safely committed to a
    private dotfile repo.
    """
    config_path.parent.mkdir(parents=True, exist_ok=True)

    phoenix_key_line = (
        f'phoenix_api_key = "{phoenix_api_key}"'
        if phoenix_api_key
        else '# phoenix_api_key = "..."   # or set PHOENIX_API_KEY in the environment'
    )
    google_key_line = (
        f'google_api_key = "{google_api_key}"'
        if google_api_key
        else '# google_api_key = "..."   # or set GOOGLE_API_KEY in the environment'
    )
    agent_runner_line = (
        f'agent_runner = "{agent_runner}"' if agent_runner else '# agent_runner = "module.path:ClassName"'
    )

    body = dedent(
        f"""
        # Nengok local configuration.
        # Generated by `nengok init`. Safe to edit by hand.

        [nengok]
        phoenix_base_url = "{phoenix_base_url}"
        {phoenix_key_line}
        {google_key_line}
        project_identifier = "{project_identifier}"
        {agent_runner_line}
        """
    ).lstrip()

    config_path.write_text(body, encoding="utf-8")
    return config_path
