"""
Write fix artifacts to the local `artifacts/` directory.

For every accepted fix we drop three files in a per-cluster subdirectory:

    <cluster_id>/prompt.md         The proposed prompt body
    <cluster_id>/regression.json   The generated regression dataset
    <cluster_id>/rca.md            A human-readable root-cause analysis

The dashboard reads these directly off disk to render its approval view,
so the on-disk shape is part of Nengok's public surface and must stay
stable across releases.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from nengok.core.observer.redactor import Redactor
from nengok.core.types import Cluster, FixArtifact, PromptProposal, RegressionTestCase, Verification
from nengok.core.verifier.manifest import write_manifest
from nengok.utils.logging import get_logger

logger = get_logger(__name__)


@dataclass
class ArtifactWriter:
    root: Path
    redactor: Redactor | None = None

    def write(
        self,
        *,
        cluster: Cluster,
        cases: list[RegressionTestCase],
        proposal: PromptProposal,
        verification: Verification,
    ) -> FixArtifact:
        cluster_dir = self.root / cluster.cluster_id
        cluster_dir.mkdir(parents=True, exist_ok=True)

        prompt_path = cluster_dir / "prompt.md"
        dataset_path = cluster_dir / "regression.json"
        rca_path = cluster_dir / "rca.md"

        redactor = self.redactor or Redactor(rules=[])

        prompt_path.write_text(_render_prompt(proposal, redactor), encoding="utf-8")
        dataset_path.write_text(
            json.dumps([case.model_dump(mode="json") for case in cases], indent=2),
            encoding="utf-8",
        )
        rca_path.write_text(
            _render_rca(cluster, proposal, verification, redactor),
            encoding="utf-8",
        )

        write_manifest(
            cluster_dir,
            cluster_id=cluster.cluster_id,
            artifact_paths=[prompt_path, dataset_path, rca_path],
        )

        logger.info("Wrote artifacts for cluster '%s' to %s", cluster.name, cluster_dir)

        return FixArtifact(
            cluster_id=cluster.cluster_id,
            prompt_path=str(prompt_path),
            dataset_path=str(dataset_path),
            rca_path=str(rca_path),
            verification=verification,
        )


def _render_prompt(proposal: PromptProposal, redactor: Redactor) -> str:
    return (
        "# Proposed prompt (Nengok)\n\n"
        f"> Cluster: `{proposal.cluster_id}`  \n"
        f"> Generated: {datetime.now(UTC).isoformat(timespec='seconds')}\n\n"
        "## Rationale\n\n"
        f"{redactor.redact(proposal.rationale)}\n\n"
        "## Baseline prompt\n\n"
        "```\n"
        f"{redactor.redact(proposal.baseline_prompt)}\n"
        "```\n\n"
        "## Prompt body\n\n"
        "```\n"
        f"{redactor.redact(proposal.proposed_prompt)}\n"
        "```\n"
    )


def _render_rca(
    cluster: Cluster,
    proposal: PromptProposal,
    verification: Verification,
    redactor: Redactor,
) -> str:
    h = cluster.hypothesis
    return (
        f"# Root-cause analysis — {cluster.name}\n\n"
        f"_Generated by Nengok on {datetime.now(UTC).isoformat(timespec='seconds')}_\n\n"
        "## Summary\n\n"
        f"{(redactor.redact(h.summary) if h else 'No hypothesis recorded.')}\n\n"
        "## Expected vs. observed\n\n"
        f"- **Expected:** {(redactor.redact(h.expected_behavior) if h else 'n/a')}\n"
        f"- **Observed:** {(redactor.redact(h.actual_behavior) if h else 'n/a')}\n"
        f"- **Likely cause:** {(redactor.redact(h.likely_cause) if h else 'n/a')}\n\n"
        "## Experiment\n\n"
        f"- Baseline pass rate: {verification.experiment.baseline_pass_rate:.0%}\n"
        f"- Fix pass rate: {verification.experiment.fix_pass_rate:.0%}\n"
        f"- Golden baseline: {verification.experiment.golden_baseline_pass_rate:.0%}\n"
        f"- Golden fix: {verification.experiment.golden_fix_pass_rate:.0%}\n\n"
        "## Proposal rationale\n\n"
        f"{redactor.redact(proposal.rationale)}\n"
    )
