"""
Write fix artifacts to the local `artifacts/` directory.

For every accepted fix we drop three files in a per-cluster subdirectory:

    <cluster_id>/prompt.md         The proposed prompt body
    <cluster_id>/regression.json   The generated regression dataset
    <cluster_id>/rca.md            A human-readable root-cause analysis

The dashboard reads these directly off disk to render its approval view,
so the on-disk shape is part of Nengok's public surface and must stay
stable across releases.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from nengok.core.types import Cluster, FixArtifact, PromptProposal, RegressionTestCase, Verification
from nengok.utils.logging import get_logger

logger = get_logger(__name__)


@dataclass
class ArtifactWriter:
    root: Path

    def write(
        self,
        *,
        cluster: Cluster,
        cases: list[RegressionTestCase],
        proposal: PromptProposal,
        verification: Verification,
    ) -> FixArtifact:
        cluster_dir = self.root / cluster.cluster_id
        cluster_dir.mkdir(parents=True, exist_ok=True)

        prompt_path = cluster_dir / "prompt.md"
        dataset_path = cluster_dir / "regression.json"
        rca_path = cluster_dir / "rca.md"

        prompt_path.write_text(_render_prompt(proposal), encoding="utf-8")
        dataset_path.write_text(
            json.dumps([case.model_dump(mode="json") for case in cases], indent=2),
            encoding="utf-8",
        )
        rca_path.write_text(_render_rca(cluster, proposal, verification), encoding="utf-8")

        logger.info("Wrote artifacts for cluster '%s' to %s", cluster.name, cluster_dir)

        return FixArtifact(
            cluster_id=cluster.cluster_id,
            prompt_path=str(prompt_path),
            dataset_path=str(dataset_path),
            rca_path=str(rca_path),
            verification=verification,
        )


def _render_prompt(proposal: PromptProposal) -> str:
    return (
        "# Proposed prompt (Nengok)\n\n"
        f"> Cluster: `{proposal.cluster_id}`  \n"
        f"> Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}\n\n"
        "## Rationale\n\n"
        f"{proposal.rationale}\n\n"
        "## Prompt body\n\n"
        "```\n"
        f"{proposal.proposed_prompt}\n"
        "```\n"
    )


def _render_rca(cluster: Cluster, proposal: PromptProposal, verification: Verification) -> str:
    h = cluster.hypothesis
    return (
        f"# Root-cause analysis — {cluster.name}\n\n"
        f"_Generated by Nengok on {datetime.now(timezone.utc).isoformat(timespec='seconds')}_\n\n"
        "## Summary\n\n"
        f"{(h.summary if h else 'No hypothesis recorded.')}\n\n"
        "## Expected vs. observed\n\n"
        f"- **Expected:** {h.expected_behavior if h else 'n/a'}\n"
        f"- **Observed:** {h.actual_behavior if h else 'n/a'}\n"
        f"- **Likely cause:** {h.likely_cause if h else 'n/a'}\n\n"
        "## Experiment\n\n"
        f"- Baseline pass rate: {verification.experiment.baseline_pass_rate:.0%}\n"
        f"- Fix pass rate: {verification.experiment.fix_pass_rate:.0%}\n"
        f"- Golden baseline: {verification.experiment.golden_baseline_pass_rate:.0%}\n"
        f"- Golden fix: {verification.experiment.golden_fix_pass_rate:.0%}\n\n"
        "## Proposal rationale\n\n"
        f"{proposal.rationale}\n"
    )
